# Generated by Django 5.1.7 on 2025-04-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_rename_unitprice_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='unitprice',
        ),
    ]
